### ISSUE TITLE
QA Dutch Auction

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#120]
I have left a batch up for 5 days, 
the price hasn't decreasedl,
so either the react app isn't responding to price changes, 
or the dutch auction decreasing price contract isn't applying.

**Comment by orpheuslummis** [comment]
Can you confirm or explain more?

I see the batch price being 222 USDC today, whereas it started at 230.


<img width="259" alt="Screenshot 2024-02-29 at 09 35 28" src="https://github.com/orpheuslummis/AstaVerde/assets/363965/7b35314a-4d25-4575-9e80-5df0ad3da4c2">

**Comment by CoftheTMP** [comment]
Aha, yes its not at 220.. So it's going down just very slowly.. thats good. I'll keep a close track on the rate its decreasing:
<img width="279" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/2fef2a62-bff4-4eed-9d60-60224a0f859a">

So thats gone down another 2 USDC. GREAT!! 

I'm keeping this thread open, just to keep reporting on price decrease until its clear and can be resolved off.

**Comment by orpheuslummis** [comment]
as per the configuration of the current test deployment, the price floor is 40 therefore that's where the price should settle.

**Comment by CoftheTMP** [comment]
And its 212 today on the 12th of March

**Comment by orpheuslummis** [comment]
Please confirm if this is still opening in the latest build @CoftheTMP
