### ISSUE TITLE
Test Server Help Needed

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#122]
(base) myname@mynameslaptop AstaVerde % ./mint.sh
Image astaverde already exists.
Minting NFTs on the base-sepolia network, with contract 0xe1708FA6bb2844D5384613ef0846F9Bc1e8eC55E...
Using the metadata from example_nftdata/nft_metadata.csv and images from example_nftdata/images/...

> astaverde@0.0.1 task:mint
> node ./scripts/mint.mjs

file:///app/scripts/mint.mjs:175
            reject(new Error(`Image ${imagepath} does not exist.`));
                   ^

Error: Image example_nftdata/images/7.jpg does not exist.
    at CsvParser.<anonymous> (file:///app/scripts/mint.mjs:175:20)
    at CsvParser.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.11.1
Minting process completed.
(base) myname@mynameslaptop AstaVerde %

**Comment by CoftheTMP** [comment]
I realised I might not have saves that metadata.csv so I did it and re-ran it.

Now it's stuck waiting for a login, but I'm not getting the email this time. I did last time I tried this 10 mins ago..

<img width="562" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/f5d98645-5767-4281-8218-914eb06b9eb9">

**Comment by CoftheTMP** [comment]
Email came through, it worked, mint went online. Sorted. Just waiting to see if the image on the batch front 'unbreaks' its broken for now

**Comment by CoftheTMP** [comment]
images unbroken, just took a few mins. Great

**Comment by orpheuslummis** [comment]
It appears a bit clunky but I’m glad you’re finding out that it works
