### ISSUE TITLE
EcoAsset Page layout

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#127]
Please can we have the whole image showing here. We need the name and description fields to be shown, that where I will put the URLs:
<img width="1145" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/757e49fa-c6d9-47bc-af1f-b97ac515f392">

- Add name and description fields to what can be seen on the token page
- Change image size to fit actual upload image.

**Comment by orpheuslummis** [comment]
implemented in https://github.com/orpheuslummis/AstaVerde/commit/2bf26f310d031a7dc477dfd28a134dd3931ac558
