### ISSUE TITLE
Click on batch in market to see Tokens in it

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#128]
On the market page, to be able to click on the 'card' and then see a list of the tokens in that batch. Like happens on the redeem page for your owned ecoassets. To be able to do that for the ecoassts owned by the owner wallet.

<img width="901" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/ef016fd7-fe3c-4b8d-abb7-a0269946374f">

- Clickable cards to see tokens in the batch

**Comment by orpheuslummis** [comment]
implemented in https://github.com/orpheuslummis/AstaVerde/commit/2bf26f310d031a7dc477dfd28a134dd3931ac558
