### ISSUE TITLE
Bought very old batch but price went up

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#130]
I minted a batch and it listed at 210USDC
I bought an old batch today at 176 per item something like that. So way over 4 days.
Then minted a second batch
and it listed at 220USDC
It should have minted at 200USDC as the last batch to sell took over 4 days. Meaning the price is too high and so it needs to drop:
<img width="1080" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/f286ee73-8685-4dc7-9454-60d7a01f453f">

And then not making any further purchases another batch was minted and it came out at 230USDC so up another 10 as if a batch had sold out sooner that 2 days:
<img width="1475" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/033e1d79-5384-4546-9bba-90056800412c">

Another batch minted and it goes up another 10 to 240USDC, which is fine, as long as the last batch sold was sold in less than 2 day.
<img width="1459" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/56349a1b-cbb4-4112-98fc-25c5b72e6d56">

Now I'm going to buy out the oldest batch I still have listed 176USDC must have been there for 2 weeks. And then mint a new batch. I would expect the new batch to mint at 230USDC, 10 less than the previous one.
But: its gone up to 250USDC
<img width="1335" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/0b4f8e55-90f6-4647-a1a7-5bcfb454b01e">

So the re-pricing code isn't quite doing what we would like it to.

**Comment by orpheuslummis** [comment]
please confirm @CoftheTMP if this is still happening in latest build

**Comment by CoftheTMP** [comment]
Bought a new batch and then minted again, price increased perfectly.

I will try a same price in 2 days and a decrease price two days later.

**Comment by CoftheTMP** [comment]
I need to leave no batches bought now. I've changed the threshold to 1 and 2 days. So I believe that If I buy the next batch on Friday... then the one after should go down.

**Comment by CoftheTMP** [comment]
We're considering this working

**Comment by orpheuslummis** [comment]
I suggest adding to the #154 any further ideas!
