### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#132]
Do you have any insight into these broken images, it’s very strange. I don’t suppose the CIDs overlap as they are the same images or something?

**Comment by orpheuslummis** [comment]
@aeither any thoughts?

**Comment by aeither** [comment]
can the images be open in the browser?

**Comment by orpheuslummis** [comment]
@CoftheTMP Can you explain where you see broken images?
Thank you
<img width="1122" alt="Screenshot 2024-05-07 at 11 01 05" src="https://github.com/orpheuslummis/AstaVerde/assets/363965/62bc84ea-497e-4099-88a2-116890fbeaa6">

**Comment by orpheuslummis** [comment]
@CoftheTMP will provide a default image #107  instead
