### ISSUE TITLE
Everything About Eco Assets

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#135]
Please put a space in the title -> Eco Assets
And remove whats there at the moment. Replacing it with only this embeded image, the two links and the question statement:
<img width="1491" alt="Everything About Eco Assets Item 1" src="https://github.com/user-attachments/assets/69c7c032-cc03-4c02-949a-181826b88723">

Single occurrence carbon removal from biochar:
https://www.youtube.com/watch?v=RYQPxhGwrUk

Explore the features: 
https://xd.adobe.com/view/642e9fdf-2a25-4424-a4d0-d68c748a8c2b-317d/?fullscreen

If you have any questions contact chris@bionerg.com

**Comment by orpheuslummis** [comment]
TBD if possible to embed with iframe

**Comment by orpheuslummis** [comment]
on which page: https://asta-verde.vercel.app/ecoassets or https://asta-verde.vercel.app/about?

**Comment by CoftheTMP** [comment]
On https://asta-verde.vercel.app/ecoassets:

Eco Assets
Eco asset production is the core of our mission. These digital assets make the semi-tangible commodity of ‘carbon removal’ into a single occurance for a specific tonne. They do this by gathering all of the proofs and audits that someone would need to know exactly how much carbon was removed without being at the site, and then putting them in an NFT together to be exchanged and redeemed.

The eco asset shows a picture of the production and usage of the biochar that was audited for the specific tonne of carbon removed.

Components of an Eco Asset
Item ID: A unique identifier in the sequence of eco assets
Producer wallet: The digital address of the biochar producer Description: The description contains the link to the redacted audit report image hosted on the blockchain. Which specific tonne from the audit that you are purchasing.  The link to the production usage image hosted on the blockchain. And the link to the Methodology audited against.

Every tonne of carbon removal in eco assets has been audited for an independent auditors opinion for how many tonnes are removed in accordance with ISO 14064-3.  This includes meeting the EU’s concept of additionality (hyperlink).

Producers receive their payments directly from the buyer, and you can following their local development from this on Bionerg (hyperlink press releases).

{Eco Asset Guide (PDF)} (update link and image)
{Explore the eco asset} (https://xd.adobe.com/view/642e9fdf-2a25-4424-a4d0-d68c748a8c2b-317d/? fullscreen)
[Everything about eco asset.pdf](https://github.com/user-attachments/files/16762885/Everything.about.eco.asset.pdf)

**Comment by orpheuslummis** [comment]
fixed in  https://github.com/orpheuslummis/AstaVerde/commit/1e754a1b2dccb9f7d7af6c3884b6a01eb65b5cf0
