### ISSUE TITLE
About

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#137]
Just some minor changes for trademark
In the FAQ
Why don't the Ethereums work here to buy EcoAssets? -> change EcoAssets to eco assets

and add one more FAQ

Q: What do I need to buy eco assets?
A: You need two currencies: 
1, enough USDC to make the auction price, and 
2, a few dollars worth of Ethereums ON Base to pay for the transaction gas.

**Comment by orpheuslummis** [comment]
@CoftheTMP please review https://asta-verde.vercel.app/about and if satisfying, close the issue

**Comment by CoftheTMP** [comment]
Change:
{Change Read everything about Eco Assets}

To 
{Eco Asset Guide (PDF)} (update link and image)
{Explore the eco asset} (https://xd.adobe.com/view/642e9fdf-2a25-4424-a4d0-d68c748a8c2b-317d/? fullscreen)
[Everything about eco asset.pdf](https://github.com/user-attachments/files/16762909/Everything.about.eco.asset.pdf)

---
Add one more FAQ:
Q: How do I create a wallet and connect it 
A: You can use many browser extensions such as Coinbase wallet, Rainbow wallet, Metamask, Kraken wallet, Rabby wallet and others. 
To move funds from your bank to your wallet, you will use a regulated exchange such as Coinbase, Kraken, or Revolut depending on your country. 
Once you have your funds on an exchange, you can move them to your wallet to purchase eco assets. 

Note: Different exchanges and wallets will have different or no fees to get USDC on Base and Ethereum on Base.

**Comment by orpheuslummis** [comment]
should be fixed in latest build
