### ISSUE TITLE
Auth and AuthCall

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#138]
https://eips.ethereum.org/EIPS/eip-3074

**Comment by orpheuslummis** [comment]
?

**Comment by CoftheTMP** [comment]
Sponsored transactions, eco assets can be bought with USDC only and the signing cost is paid by owner. Using EIP 3074 Auth to 'sponsor all transactions'. The bounty for this was emailed.

**Comment by orpheuslummis** [comment]
The EIP https://eips.ethereum.org/EIPS/eip-3074 is still in review stage, and as I understand it may go live in the next Ethereum upgrade which could land in later in 2024 or in 2025.
Is Base somehow supporting it early?
I'm closing this for now. Feel free to re-open once the EIP is confirmed to be officially supported.
