### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#142]
Issue 1:
Mint function on the front end gives this error:
<img width="1512" alt="Screenshot 2024-08-30 at 18 14 58" src="https://github.com/user-attachments/assets/24cde07a-b78a-4b09-a268-2711a989e105">

**Comment by CoftheTMP** [comment]
Issue 2.
Batch disappears after around 10 seconds. It didn't when we could still see Sold Out batches, so perhaps the hiding of Sold Out batches is causing this.
<img width="1509" alt="Screenshot 2
<img width="1508" alt="Screenshot 2024-08-30 at 18 17 51" src="https://github.com/user-attachments/assets/9f992adb-3761-4282-b20c-e7cbd9b5b76d">
024-08-30 at 18 17 59" src="https://github.com/user-attachments/assets/e35ecf8e-a76f-44e7-9a62-86bb63673164">

**Comment by orpheuslummis** [comment]
What's DA?
Note that it is preferable to create one GitHub issue per issue.

Issue 2 fixed with https://github.com/orpheuslummis/AstaVerde/commit/6afb6aa2a4f9d4bcaf40c8e7cf2f3d22d3742274

**Comment by orpheuslummis** [comment]
issue 1 fixed, https://github.com/orpheuslummis/AstaVerde/commit/38c9ba4584b72ec0905aab467c5f5867b9f0ffaf
