### ISSUE TITLE
Mint function failed 

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#145]
<img width="1512" alt="Screenshot 2024-09-07 at 21 00 06" src="https://github.com/user-attachments/assets/7159d73b-47ca-4fcc-aebb-f8e57fc05cd8">

**Comment by orpheuslummis** [comment]
thanks for flagging, should be fixed in latest build. please confirm.

**Comment by CoftheTMP** [comment]
Progress reports :o!!! This mint page is legendary!
