### ISSUE TITLE
Redeem page error

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#146]
<img width="1370" alt="Screenshot 2024-09-08 at 16 16 11" src="https://github.com/user-attachments/assets/df208c8f-6bb1-497f-9538-d90501dd7314">
<img width="1348" alt="Screenshot 2024-09-08 at 16 16 18" src="https://github.com/user-attachments/assets/bad45dc0-4bba-4fed-a2d8-700d06b690bf">

**Comment by orpheuslummis** [comment]
This should be fixed on the latest development branch. Please confirm.  @CoftheTMP

**Comment by CoftheTMP** [comment]
It works perfectly
