### ISSUE TITLE
Decrease rate is $1 a day

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#148]
<img width="961" alt="image" src="https://github.com/user-attachments/assets/2cac2b95-c9ea-4492-9e88-282524d0fb2a">

**Comment by orpheuslummis** [comment]
this is fixed, it is available in admin page.

**Comment by CoftheTMP** [comment]
Yeah this was great, now I think this decrease has somehow been stopped.
