### ISSUE TITLE
Writing on button goes invisible

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#149]
Small thing really
<img width="672" alt="image" src="https://github.com/user-attachments/assets/5ce445c6-a5e2-4ecc-904f-3d6355476c9e">

**Comment by orpheuslummis** [comment]
This is fixed in the latest development benchmark, please confirm.  @CoftheTMP

**Comment by CoftheTMP** [comment]
The colours of really stylish
