### ISSUE TITLE
Select all to redeem

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#150]
If its easy to put select all to redeem, that would be ideal.

<img width="966" alt="image" src="https://github.com/user-attachments/assets/8cee18b2-7292-4df4-a762-58fb12f9412a">

**Comment by orpheuslummis** [comment]
Good idea

**Comment by orpheuslummis** [comment]
@CoftheTMP this wasn't the intent on the latest development branch. Can you confirm and close the issue?

**Comment by CoftheTMP** [comment]
Really nice
