### ISSUE TITLE
Redeem and NFT Location?

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#151]
Something strange is that the eco assets don't show up in my metamask wallet. I don't know if thats because metamask and base sepolina are not really matched that well. But I was hoping to see them there, so that I would know I can sell them on opensea, and also to understand where the Redeemed change occurs, so it can be demonstrated clearly to show a sort of auditor that this redeem has happened.

**Comment by Darrenpeaker** [comment]
> Something strange is that the eco assets don't show up in my metamask wallet. I don't know if thats because metamask and base sepolina are not really matched that well. But I was hoping to see them there, so that I would know I can sell them on opensea, and also to understand where the Redeemed change occurs, so it can be demonstrated clearly to show a sort of auditor that this redeem has happened.

@CoftheTMP It seems like you're having trouble seeing the eco assets in your Metamask wallet.It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by orpheuslummis** [comment]
The tokens show up on Opensea: https://testnets.opensea.io/collection/unidentified-contract-41df5df0-40e8-4e99-a95c-bbe8

Off-chain and off-site redeem visibility will require a special program.
