### ISSUE TITLE
QA Mint Page Font Colour

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#156]
<img width="563" alt="image" src="https://github.com/user-attachments/assets/cae1aebd-9d27-451e-a94b-a1f95b54bf01">

**Comment by orpheuslummis** [comment]
This is fixed in the latest commit, as of now. Please confirm and close the issue @CoftheTMP

**Comment by CoftheTMP** [comment]
This looks and works smoothly and looks really sleek
