### ISSUE TITLE
Receive producer payments

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#164]
So far I don't receive producer payments even though I put in the owner wallet as the producer
<img width="313" alt="image" src="https://github.com/user-attachments/assets/2dacb847-fdf6-4da1-9877-bb8eb0ca4e9e">

**Comment by orpheuslummis** [comment]
what is the address in question?
i think the transfers are working but you don't see the 'fake USDC' token in your wallet perhaps.
i recommend looking at the blockchain explorer https://base-sepolia.blockscout.com/

**Comment by CoftheTMP** [comment]
Ok interesting I will try with another wallet as the producer. 161 goes to the Producer and then 57 of some token goes to the owner. It doesn't quite add up to 230, but I'll see what it looks like to another wallet.
<img width="894" alt="image" src="https://github.com/user-attachments/assets/6e0b1115-9695-4a15-b5d2-6230fe118079">

**Comment by CoftheTMP** [comment]
Ok yes the splitting is working well, this is really great to see. I'm guessing 57 of the unamed token has an equivalent value to 69 USDC.
<img width="878" alt="image" src="https://github.com/user-attachments/assets/f310e0f9-61a4-4024-b7d9-91356aed6968">

**Comment by CoftheTMP** [comment]
Ok I've claimed the platform funds, now I will do one more item purchase, and claim again
<img width="753" alt="image" src="https://github.com/user-attachments/assets/d758b936-d8cf-4da7-ad70-86a3d8d62739">
