### ISSUE TITLE
Failed to change decrease batch rate

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#165]
<img width="1512" alt="Screenshot 2024-10-09 at 12 28 32" src="https://github.com/user-attachments/assets/53626386-f9ed-41c8-a077-2860f0066b4e">

**Comment by orpheuslummis** [comment]
I think that was fixed?

**Comment by CoftheTMP** [comment]
So Price Decrease Rate seems to have maybe become confused with the Price Delta of a new minted batch price

**Comment by CoftheTMP** [comment]
Closing all decrease QAs
