### ISSUE TITLE
Prices haven't decreased 26 hours later

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#167]
The batch that minted for 250 usdc is still 250 usdc, I minted it at 8pm yesterday its after 10pm today.
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/1919bdd3-b356-4a62-9d09-3ad483cbc46f">

**Comment by orpheuslummis** [comment]
The logic currently is that the price will decrease for every day after the `dayDecreaseThreshold`

**Comment by CoftheTMP** [comment]
This QA is about the daily price drop. Each day the price would decrease by $1. You changed that to $5.

I wonder if two different price deltas have become confused now? There used to be a price decrease, but now theres a price delta which I'm now guessing relates to the new minted start price?
<img width="598" alt="image" src="https://github.com/user-attachments/assets/d1848c51-97cb-402e-ad09-2b14674972ec">

**Comment by CoftheTMP** [comment]
This QA is about how the price use to be $209 after a day, then $208 and I said the decrease is too slow! And you increased it to 5 but then we wanted to be able to change that decrease in admin

**Comment by CoftheTMP** [comment]
Ok batch 7 is down to $230
