### ISSUE TITLE
README documentation and videos showing core flows

### ISSUE THREAD

**Issue by orpheuslummis** [orpheuslummis/AstaVerde#20]
- buyer and redeemer journey
- platform owner journey

**Comment by orpheuslummis** [comment]
include https://github.com/orpheuslummis/AstaVerde/pull/33 in the video

**Comment by aeither** [comment]
video demo on core flow 
https://www.loom.com/share/728dfc0390704122a436e782c834b678?sid=593a9904-5605-494f-a679-7f8c0bcb2bf0
