### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by orpheuslummis** [orpheuslummis/AstaVerde#23]
- [ ] Add Our Story
- [ ] Add Bugcrowd link when approved
- [ ] Add Want to be or set up a biochar producer? Link https://www.c-go.com/about

**Comment by CoftheTMP** [comment]
EcoTradeZone revolutionizes the way biochar production is valued and traded. It stands as a unique marketplace where the diligent work of biochar producers is transformed into tangible tokens, each representing their creation. These tokens are not just symbolic; they embody the genuine environmental impact of the producers' efforts, quantified as one tonne of carbon dioxide equivalent. At EcoTradeZone, these tokens can be both purchased and redeemed, offering a direct and meaningful way to participate in climate action. This system not only incentivizes biochar production but also connects the efforts of producers with individuals and organizations eager to contribute to global carbon reduction. By making each token a claimable representation of a real-world environmental benefit, EcoTradeZone fosters a new, eco-conscious economy where sustainable practices are both recognized and rewarded.

**Comment by orpheuslummis** [comment]
<img width="612" alt="Screenshot 2024-01-12 at 21 29 15" src="https://github.com/orpheuslummis/AstaVerde/assets/363965/61038898-8da8-4492-9124-55af6dfcd962">
I see you edited my comment with this.
Can you expand on what these are?

**Comment by CoftheTMP** [comment]
About us story.

On the about page. I need one paragraph section called Our Story and the option to write a story in there. Also a holder picture that I can switch for one we want there.

Then a second paragraph called Bug Support
With a paragraph that I can change about how you can earn rewards for bug catching (they're going to be small rewards for now :( )
and then a link button that takes you to our bug report page. Which I've set up but its being approved.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by CoftheTMP** [comment]
<img width="1387" alt="image" src="https://github.com/orpheuslummis/AstaVerde/assets/156298319/3da94cb3-bf02-4f8f-bc42-5b4016e11745">

**Comment by orpheuslummis** [comment]
vertical

**Comment by orpheuslummis** [comment]
include FAQ in About page

**Comment by CoftheTMP** [comment]
So first paragraph with background pastel colour:
EcoTradeZone revolutionizes the way biochar production is valued and traded. It stands as a unique marketplace where the diligent work of biochar producers is transformed into tangible tokens, each representing their creation. These tokens are not just symbolic; they embody the genuine environmental impact of the producers' efforts, quantified as one tonne of carbon dioxide equivalent. At EcoTradeZone, these tokens can be both purchased and redeemed, offering a direct and meaningful way to participate in climate action. This system not only incentivizes biochar production but also connects the efforts of producers with individuals and organizations eager to contribute to global carbon reduction. By making each token a claimable representation of a real-world environmental benefit, EcoTradeZone fosters a new, eco-conscious economy where sustainable practices are both recognized and rewarded.

2nd paragraph with no colour:
Bug Report
Please tell us about any bugs you find, we want to keep this place running smoothly to help producers get their earnings
Bug report link button

3rd paragraph with pastel colour:

FAQ
Q: Why don't the Ethereums work here to buy EcoAssets?
A: This is on the Base network, which runs in parallel to the main Ethereum network and has responsibilities to it in terms of its data integrity. But this means that you need the currencies that are used on this Base network. Coinbase wallets work natively with Base and the currency that you purchase in is USDC so make sure that the currency you have on your base network wallet.

**Comment by orpheuslummis** [comment]
If this is ready to be included @CoftheTMP ?

**Comment by CoftheTMP** [comment]
EcoTradeZone revolutionizes the way biochar production is valued and traded. It stands as a unique marketplace where the diligent work of biochar producers is transformed into tangible tokens, each representing their creation. These tokens are not just symbolic; they embody the genuine environmental impact of the producers' efforts*, quantified as one tonne of carbon dioxide equivalent. At EcoTradeZone, these tokens can be both purchased and redeemed, offering a direct and meaningful way to participate in climate action. This system not only incentivizes biochar production but also connects the efforts of producers with individuals and organizations eager to contribute to global carbon reduction. By making each token a claimable representation of a real-world environmental benefit, EcoTradeZone fosters a new, eco-conscious economy where sustainable practices are both recognized and rewarded.

*Read Everything about EcoAssets before buying

Bug Report
Please tell us about any bugs you find, we want to keep this place running smoothly to help producers get their earnings. There may be some small rewards for bugs found, depending on the bug.
Email chris@bionerg.com
Title: Bug Found

FAQ
Q: Why don't the Ethereums work here to buy EcoAssets?
A: This is on the Base network, which runs in parallel to the main Ethereum network and has responsibilities to it in terms of its data integrity. But this means that you need the currencies that are used on this Base network. Coinbase wallets work natively with Base and the currency that you purchase in is USDC so make sure that the currency you have on your base network wallet.
Q: What do I need to know about using my wallet here?
Transactions here are conducted using Base native USDC, issued by Circle. For more understanding:
Learn about Base: [Base Information](https://base.mirror.xyz/Ouwm--AtTIVyz40He3FxI0fDAC05lOQwN6EzFMD_2UM)
Base from Coinbase: [Coinbase on Base](https://help.coinbase.com/en/coinbase/other-topics/other/base)
USDC on Base: [USDC Details](https://www.circle.com/blog/usdc-now-available-natively-on-base)

**Comment by orpheuslummis** [comment]
assigning @aeither to integrate the content into the frontend
