### ISSUE TITLE
Integrating colors and logo

### ISSUE THREAD

**Issue by orpheuslummis** [orpheuslummis/AstaVerde#26]

**Comment by orpheuslummis** [comment]
@CoftheTM

**Comment by CoftheTMP** [comment]
Did you have the rgb for this?

**Comment by CoftheTMP** [comment]
rgb(88, 172, 96) is the green

**Comment by CoftheTMP** [comment]
rgb(61, 155, 233) is the blue

**Comment by CoftheTMP** [comment]
![ecotradezone](https://github.com/orpheuslummis/AstaVerde/assets/156298319/68d6e428-7625-4033-bb07-5843fa0032c7)
