### ISSUE TITLE
Arrival pop up (know before entering the site)

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#28]
welcome to EcoTradeZone, we need your agreement that you understand the following

- [ ] Write about what these asset represent
- [ ] Write what we know about redemption so far
- [ ] write about Base wallets and USDC

**Comment by orpheuslummis** [comment]
We currently have the modal implemented, just waiting for content.

**Comment by CoftheTMP** [comment]
Welcome to EcoTradeZone
BEFORE ENTERING the following must be understood
- You are now entering a web3 zone, this means that you will need to connect your crypto wallet to participate. 
- Buying and selling tokens have local responsibilities in terms of tax and declaration, if you proceed into this zone you will be fully responsible for what these are for you.
- The zone you are entering handles transaction on Base native USDC issued by Circle. These links explain both of these:
Base: https://base.mirror.xyz/Ouwm--AtTIVyz40He3FxI0fDAC05lOQwN6EzFMD_2UM
About Base from Coinbase: https://help.coinbase.com/en/coinbase/other-topics/other/base
USDC on Base: https://www.circle.com/blog/usdc-now-available-natively-on-base
- You will need your crypto wallet to interact with Base for this, the coinbase wallet does this automatically:
How to use your crypto wallet with this Base zone: https://docs.base.org/using-base/
- Understand what these EcoAssets are on the 'Everything about EcoAssets' page
- Redemption is non reversible. When you redeem an EcoAsset, it loses its intrinsic tonne of carbon dioxide equivalent and your wallet is the proof about when you made this choice.

**Comment by orpheuslummis** [comment]
If this is ready to be included @CoftheTMP ?

**Comment by CoftheTMP** [comment]
**Welcome to the EcoTradeZone: Important Information Before You Enter**

Web3 Zone Access: You're about to enter a web3 zone. This requires connecting your crypto wallet to participate. Make sure your wallet is ready.
Tax and Legal Responsibilities: Be aware that buying and selling tokens involves local tax and declaration responsibilities. By entering, you accept full responsibility for complying with these obligations. More details are available in our Terms of Service.
Transaction Currency: Transactions here are conducted using Base native USDC, issued by Circle. For more understanding:
Learn about Base: [Base Information](https://base.mirror.xyz/Ouwm--AtTIVyz40He3FxI0fDAC05lOQwN6EzFMD_2UM)
Base from Coinbase: [Coinbase on Base](https://help.coinbase.com/en/coinbase/other-topics/other/base)
USDC on Base: [USDC Details](https://www.circle.com/blog/usdc-now-available-natively-on-base)
Crypto Wallet Compatibility: You'll need your crypto wallet for interactions on Base. Coinbase wallets are automatically compatible. For other wallets, you may need to add Base manually. Learn more on our 'About and FAQ’s' page.
Understanding EcoAssets: Before you buy, familiarize yourself with EcoAssets on our 'Everything about EcoAssets' page. Know what you’re investing in.
Non-reversible Redemption: Once you redeem an EcoAsset, it loses its intrinsic carbon dioxide equivalent value. This redemption will be recorded in your wallet.
By clicking to enter the EcoTradeZone, you acknowledge that you have read and understood these terms.

**Comment by orpheuslummis** [comment]
assigning @aeither to integrate the content into the frontend
