### ISSUE TITLE
Everything about EcoAssets

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#30]
- [ ] NFT intor
- [ ] Breakdown of the elements of an ecoasset
- [ ] ownership post purchase
- [ ] non-ownership before
- [ ] Keeping one
- [ ] endurance

**Comment by orpheuslummis** [comment]
Is this to be a page on the site?

**Comment by CoftheTMP** [comment]
Please, its inspired by opensea.io with their long list of pages, what is blockchain what is an nft and so on. I thought we could just do it in one page with Everything about EcoAssets

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by orpheuslummis** [comment]
<img width="1171" alt="Screenshot 2024-01-14 at 17 34 27" src="https://github.com/orpheuslummis/AstaVerde/assets/363965/bc1a982a-37c6-41c2-a03b-98453a22fe22">

**Comment by orpheuslummis** [comment]
it could be the landing page too

**Comment by CoftheTMP** [comment]
I would like to introduce you to the EcoAsset
{Image of an EcoAsset}
Theres as much below the hood as on the front of one of these beauties
On the front you will see the time date and location where some amazing biochar producers have been working hard to make high quality biochar making the world a bit better.
You'll be able to see from the picture and the location that this all adds up :)
Now lets go below the hood:
{ItemID, Producer Wallet, Impartial verification number}
The Item ID is the next in the sequence of EcoAssets 
Producer wallet is the wallet of the team that is working hard day in day out to make this world better with biochar
Audit ID is the impartial verification at great expense to a company that doesn't get paid by from the sale of EcoAssets but from auditing the data against robust methodology for biochar production. This methodology includes the 'additionality' of the project. The environmental sustainability of the biomass. And the application of biochar.
European Union concept of additionally document: https://www.europarl.europa.eu/RegData/etudes/note/join/2012/433785/EXPO-DEVE_NT(2012)433785_EN.pdf

With all of these pieces on the face of it and under the hood having been collected and verified a proposal is put together on EcoTradeZone. Where if purchased a promised share will go to the producer and the owner (EcoTradeZone).

Then the EcoAssets creation is completed as a result of the transactional purchase and the asset is in the buyers wallet!

**Comment by orpheuslummis** [comment]
If this is ready to be included @CoftheTMP ?

**Comment by CoftheTMP** [comment]
I mean. Yes, you can add them all. Then we have a chance to deploy to test net by Saturday.. but I’ll need to adjust them all.. it’s been such a busy week I couldn’t lock all this content down

**Comment by CoftheTMP** [comment]
[What is an EcoAsset.pdf](https://github.com/orpheuslummis/AstaVerde/files/14101879/What.is.an.EcoAsset.pdf)

**Comment by CoftheTMP** [comment]
[What is an EcoAsset.pdf](https://github.com/orpheuslummis/AstaVerde/files/14102020/What.is.an.EcoAsset.pdf)

**Comment by orpheuslummis** [comment]
assigning @aeither to integrate the content into the frontend

**Comment by orpheuslummis** [comment]
@CoftheTMP should we include the content of the pdf or the pdf itself? thanks for confirming.
