### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#31]
- [ ] An FAQ page that I can just copy one bulletpoints form and paste another line the same to fill it out.

**Comment by orpheuslummis** [comment]
Can you clarify what is the issue/task/offer?
I understand you want an FAQ page to be added.
If so, you can provide the content here and we can add it.

**Comment by CoftheTMP** [comment]
Yes, thats right, FAQ pages added. I'm working on the content.

If we can get at least one:

Q: dfsjdif
A: aisdndsijf

formatted and I can copy and paste that formatting to add new FAQ's in the future that would be perfect.

**Comment by orpheuslummis** [comment]
closed in favor of #23
