### ISSUE TITLE
NFT json info

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#38]
{TokenID, ProducerWallet, AuditID} And the image gets pulled from the IPFS, and thats displayed on etherscan?

Is this how it's set up?

**Comment by CoftheTMP** [comment]
{tokenIDauto, Description, ProducerWallet}

**Comment by CoftheTMP** [comment]
@orpheuslummis I think we can close this one...

**Comment by orpheuslummis** [comment]
closing in favor of #20
