### ISSUE TITLE
why increase must be higher than decrease in the contract for setAuctinoThreshold?

### ISSUE THREAD

**Issue by aeither** [orpheuslummis/AstaVerde#46]
![photo](https://github.com/orpheuslummis/AstaVerde/assets/36173828/eae63130-9911-4685-9ef8-a6679e1ec2c1)

**Comment by orpheuslummis** [comment]
https://github.com/orpheuslummis/AstaVerde/blob/44a420fb74bb4b03241d47e752c63a93a262c6a8/contracts/AstaVerde.sol#L239-L265

increase should be lower than decrease

**Comment by orpheuslummis** [comment]
closing as this answers the question
