### ISSUE TITLE
No token CID when calling "tokens"

### ISSUE THREAD

**Issue by aeither** [orpheuslummis/AstaVerde#54]
blocking Display token images from IPFS #44

when reading contract for token CID. it returns empty string.
used: 0x1857B0f7c6fcE1668CBCa34f6975fEE7398AD3a8 on base sepolia

 tokenInfo.data = [ 1n, '0x568AeD5332a07FfD06Cd8e129FCD56EB37363f40', '', false ]

const tokenCID = tokenInfo.data[2];
// tokenCID = ''

**Comment by orpheuslummis** [comment]
do you mind trying again with `0x6a877a13BA618eD8AaF36fcc879A6cf225e010D4` which is the latest testnet deployment?

**Comment by aeither** [comment]
same result
[ 1n, '0x568AeD5332a07FfD06Cd8e129FCD56EB37363f40', '', false ]
