### ISSUE TITLE
`buyBatch` gets triggered upon market load

### ISSUE THREAD

**Issue by orpheuslummis** [orpheuslummis/AstaVerde#66]
<img width="494" alt="Screenshot 2024-01-25 at 07 52 19" src="https://github.com/orpheuslummis/AstaVerde/assets/363965/80b9b80e-7ed5-4c47-a2ba-d74e5357a2c0">

Ideally the function would not be called and error unless there is an user intent for it.

**Comment by CoftheTMP** [comment]
It is kind of a downer that it says not enough balance in red when you arrive on the site. It would be appreciate if this could be fixed so it shows green.

**Comment by orpheuslummis** [comment]
this seems fixed.

**Comment by orpheuslummis** [comment]
https://github.com/orpheuslummis/AstaVerde/assets/363965/55ef5682-787b-4aca-8385-c820440587e6

actually it is an active issue

**Comment by orpheuslummis** [comment]
stale issue
