### ISSUE TITLE
Short demo video for 'events' script

### ISSUE THREAD

**Issue by orpheuslummis** [orpheuslummis/AstaVerde#72]
as part of https://github.com/orpheuslummis/AstaVerde/issues/20

**Comment by aeither** [comment]
video demo on how to read on chain events
https://www.loom.com/share/de08a8a4b0784fd5960a81587436ebe1?sid=b375192a-c874-49b3-a54b-6f34604692d9

**Comment by orpheuslummis** [comment]
closing, no time for that.
