### ISSUE TITLE
Privacy Policy Page

### ISSUE THREAD

**Issue by CoftheTMP** [orpheuslummis/AstaVerde#86]
Add a privacy policy page.

**Comment by orpheuslummis** [comment]
assigning @CoftheTMP to provide the content

**Comment by CoftheTMP** [comment]
EcoTradeZone of Bionerg Ltd. Privacy Policy
Date: 31 Jan 2024

Our contact details 
Name: Bionerg Ltd.
Address: 4th Floor, 5B The Parklands, Lostock, Bolton, BL6 4SD
Company number: 9139423
E-mail: chris@bionerg.com

The type of personal information we collect 
We do not consider public wallet addresses to be personal information.
We currently collect and process the following information:
email addresses from voluntary sign ups for alerts or bug communications

How we get the personal information and why we have it
Most of the personal information we process is provided to us directly by you for one of the following reasons:
to fulfil voluntary requests for auction alerts or bug communications.
We do not receive personal information indirectly. 

We use the information that you have given us in order to alert you to auctions if requested, or respond to your bug submission if requested. 
We may share this information with our programming partners to resolve bugs.
Under the UK General Data Protection Regulation (UK GDPR), the lawful bases we rely on for processing this information are: 
Your consent. You are able to remove your consent at any time. You can do this by contacting 
chris@bionerg.com for removal from auction alerts
chris@bionerg.com for removal from further bug discussionHow we store your personal information 
Your email address, if voluntarily given, is kept in a gmail held account with 2FA.
We keep emails for one year. We will then dispose your information by clearing those email accounts which are the sole record of your email address.
Your data protection rights
Under data protection law, you have rights including:
Your right of access - You have the right to ask us for copies of your personal information. 
Your right to rectification - You have the right to ask us to rectify personal information you think is inaccurate. You also have the right to ask us to complete information you think is incomplete. 
Your right to erasure - You have the right to ask us to erase your personal information in certain circumstances. 
Your right to restriction of processing - You have the right to ask us to restrict the processing of your personal information in certain circumstances. 
Your right to object to processing - You have the the right to object to the processing of your personal information in certain circumstances.
Your right to data portability - You have the right to ask that we transfer the personal information you gave us to another organisation, or to you, in certain circumstances.
You are not required to pay any charge for exercising your rights. If you make a request, we have one month to respond to you.
Please contact us at chris@bionerg.com for auction alert request removal, or chris@bionerg.com for bug report communication removal if you wish to make a request.
How to complain
If you have any concerns about our use of your personal information, you can make a complaint to us at chris@bionerg.com.
You can also complain to the ICO if you are unhappy with how we have used your data.
The ICO’s address:            
Information Commissioner’s Office
Wycliffe House
Water Lane
Wilmslow
Cheshire
SK9 5AF

Helpline number: 0303 123 1113
ICO website: https://www.ico.org.uk/

**Comment by orpheuslummis** [comment]
assigning @aeither to integrate the content into the frontend
